---
# tasks file for roles/ipa
- name: Update Repositories
  become: yes
  apt:
    update_cache: yes

- name: Create Ipa automation directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - '/root/.ipa_automate'

- name: Upload ipa_init.sh File
  become: yes
  copy:
    src: ipa_init.sh
    dest: /root/.ipa_automate/ipa_init.sh

- name: Change permissions on ipa_init.sh
  become: yes
  file:
    path: /root/.ipa_automate/ipa_init.sh
    mode: "u+rwx"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Run Ipa Initialization script
  become: yes
  command: /root/.ipa_automate/ipa_init.sh
  args:
    executable: /bin/bash
